[package]
name = "mik"
version = "0.1.0"
edition = "2024"

[dependencies]
swc_ecma_parser = { version = "23.0.0", features = ["typescript"] }
swc_common = { version = "14.0.3", features = ["tty-emitter"] }
llvm-sys = "211.0.0"
swc_ecma_ast = "15.0.0"
